### ISSUE TITLE
[Task] 마이페이지 이력 추가/수정/삭제

### ISSUE THREAD

**Issue by jna2158** [codestates/actorz-client#13]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 마이페이지 이력 추가/수정/삭제

### TODO
1. [x] 마이페이지 이력 추가
2. [x] 마이페이지 이력 수정
3. [x] 마이페이지 이력 삭제

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 1.5h`
- Group : `client`
- Sprint: `Sprint__2__`
- Urgency: `Middle`
