### ISSUE TITLE
[Task] 쪽지 기능 구현하기

### ISSUE THREAD

**Issue by Captainjack-kor** [codestates/actorz-client#20]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 채용자가 배우의 포트폴리오 정보를 보고 원하는 배우에게 쪽지(명함)를 발송한다. 쪽지의 내용은 채용자의 회사정보와 간략한 문장을 추가해서 보낸다. 쪽지를 받은 배우는 알림을 통해 쪽지를 확인할 수 있다.

### TODO
1. [x] 채용자로 로그인시 포스트에 쪽지 버튼을 추가한다.
2. [x] 쪽지 버튼을 클릭시에 회사정보를 해당 유저에게 전달한다.
3. [x] 쪽지를 받은 배우는 알림이 오며 알림창을 통해 쪽지를 확인할 수 있다.

### Estimated time
> Pick one
