### ISSUE TITLE
[Task] 리크루터 회원 가입시 추가정보를 등록 

### ISSUE THREAD

**Issue by Captainjack-kor** [codestates/actorz-client#28]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 리크루터 회원 가입시에는 추가적인 정보를 적는 폼이 추가로 출력되며, 사업자등록 번호 및 회사의 내용을 적게 한다. 

### TODO
1. [ ] 회원 가입시 특정 버튼이나 체크박스를 이용하여 리크루터로 회원 가입시에 추가정보 폼을 출력
2. [ ] 입력한 정보 중 사업자 번호는 api를 통해 실제 존재하는 회사인지 확인 가능해야 함
3. [ ] 모든 폼이 작성이 되고 회원가입이 진행되면 인증된 타이틀을 해당 유저에게 표시되게 한다.

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`

**Additional context**
