### ISSUE TITLE
[Task] POST 클릭시에 scrollable 기능 구현하기

### ISSUE THREAD

**Issue by Captainjack-kor** [codestates/actorz-client#5]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: POST 클릭시에 모달창을 생성하고 컨텐츠 여러 개를 scrollable 기능을 구현하여 리스트를 출력한 후 볼 수 있게한다.

### TODO
1. [x] POST 클릭시 모달 창을 생성한다.
2. [x] 생성한 모달창에 컨텐츠를 출력한다.
3. [x] 컨텐츠를 마우스 휠을 이용하여 컨텐츠를 전부 확인할 수 있다.

### Estimated time
> Pick one
