### ISSUE TITLE
[Task] 마이페이지 구현

### ISSUE THREAD

**Issue by jna2158** [codestates/actorz-client#9]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 마이페이지 화면 디자인 구현

### TODO
1. [x] 유저 정보 화면 (+수정, 삭제 버튼)
2. [x] 프로필 정보 화면 (+수정, 삭제 버튼)
3. [x] 이력 화면 (+수정, 삭제 버튼)

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__2__`
- Urgency: `High`
